services:
    bill-splitter-ui:
        build:
            context: .
        ports:
            - 3030:3030
        networks:
            - proxy
            - bill-splitter
networks:
    proxy:
        external: true
    bill-splitter:
        external: true

